project/items/forms.py
from flask_wtf import Form
from wtforms import StringField
from wtforms.validators import DataRequired


class AddItemForm(Form):
    item_title = StringField('Item Title', validators=[DataRequired()])
    item_description = StringField('Item Description', validators=[DataRequired()])
    item_comment = StringField('Item Comment', validators=[DataRequired()])

project/items/views.py
from flask import render_template, Blueprint, request, redirect, url_for, flash
from project import db
from project.models import Item
from .forms import AddItemForm

# config
items_blueprint = Blueprint('items', __name__, template_folder='templates')


# helper functions
def flash_errors(form):
    for field, errors in form.errors.items():
        for error in errors:
            flash(u"Error in the %s field - %s" % (
                getattr(form, field).label.text, error), 'info')


# routes
@items_blueprint.route('/')
def index():
    all_items = Item.query.all()
    return render_template('items.html', items=all_items)

@items_blueprint.route('/add', methods=['GET', 'POST'])
def add_item():
    form = AddItemForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            new_item = Item(form.item_title.data, form.item_description.data, form.item_comment.data)
            db.session.add(new_item)
            db.session.commit()
            flash('New item, {}, added!'.format(new_item.item_title), 'success')
            return redirect(url_for('items.index'))
        else:
            flash_errors(form)
            flash('ERROR! Item was not added.', 'error')

    return render_template('add_item.html',
                           form=form)

project/items/templates/_form_macros.html
{% macro render_field(field) %}


<dt>{{ field.label }}:

<dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <span class="error">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
</dd>


{% endmacro %}

project/items/templates/add_item.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}


<div class="add-item">

<div class="page-header">

<h2>Add a New Item</h2>

  </div>



<form action="{{ url_for('items.add_item') }}" method="post">
    {{ form.csrf_token }}

<dl>
      {{ render_field(form.item_title, placeholder="Enter item Title") }}
      {{ render_field(form.item_description, placeholder="Enter item Description") }}
      {{ render_field(form.item_comment, placeholder="Enter item Comment") }}
    </dl>

    <button class="btn btn-sm btn-success" type="submit">Add item</button>
  </form>

</div>


{% endblock %}

project/items/templates/items.html
{% extends "layout.html" %}
{% block content %}

<div class="page-header">
  <h2>Items</h2>
</div>
<div class="row">
  <div class="col-md-4">
    <table class="table table-striped" id="owned_stock_table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        {% for item in items %}
        <tr>
          <td>{{ item.item_title }}</td>
          <td>{{ item.item_description }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}

project/items/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Cookiecutter App">
    <meta name="author" content="Falk">
    <title>Cookiecutter APP</title>
    <!-- styles -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
  </head>

  <body>

    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">

        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#items-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('items.index') }}">CookieCutter APP</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="items-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="#">Item Link</a></li>
            <li><a href="{{ url_for('items.add_item') }}">Add item</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Welcome!</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div><!-- /.container -->
    </nav>

    <div class="container">
      <div class="content">
        <!-- flash messages -->
        {% for error_message in get_flashed_messages(category_filter=["error"]) %}

<div class="alert alert-danger alert-dismissible">{{ error_message }}</div>

        {% endfor %}

        {% for success_message in get_flashed_messages(category_filter=["success"]) %}

<div class="alert alert-success alert-dismissible">{{ success_message }}</div>

        {% endfor %}

        {% for info_message in get_flashed_messages(category_filter=["info"]) %}

<div class="alert alert-info alert-dismissible">{{ info_message }}</div>

        {% endfor %}

        <!-- child template -->
        {% block content %}
        {% endblock %}

      </div>
      <div class="footer">
        <hr>
        <p>Patrick Kennedy - 2016</p>
      </div>
    </div><!-- /.container -->

    <!-- scripts -->
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  </body>
</html>